### ISSUE TITLE
seu email?

### ISSUE THREAD

**Issue by luabr-fecik** [juniorots/smartTaco#1]
junior, 
qual eh o seu email?

quero te um .html que
mostra valores estranhos da Taco.

mas se voce nao estiver interessado
ou preocupado no momento para
os valores da propria Taco em si,
ignore minha mensagem.

(estou vendo se no github ha
outros que mexem com a Taco)

**Comment by juniorots** [comment]
juniorots@gmail.com

Em dom, 10 de fev de 2019 16:26, fecic <notifications@github.com escreveu:

**Comment by luabr-fecik** [comment]
valeu, @juniorots 

Deleta minha Issue.
Vou te enviar o email/arquivo.

**Comment by luabr-fecik** [comment]
@juniorots 

lembrando: deleta a issue
